---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release-java:
    name: "Pre Release (Java)"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: |
          cd gui
          ./gradlew buildAll
          cd ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            gui/client.jar
            gui/server.jar

  pre-release-arduino:
    name: "Pre Release (Arduino firmware)"
    runs-on: "ubuntu-18.04"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get install gcc-avr binutils-avr avr-libc
      - run: cd firmware
      - run: make
      - run: mv Joystick.hex Arduino_UNO_R3.hex

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            Arduino_UNO_R3.hex