---
name: "pre-release"

on:
  push:
    branches:
      - "master"
      - "java-fx"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-18.04" # Required by Arduino firmware, until 20.04 is tested

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: |
          cd gui
          ./gradlew buildAll
          cd ..

      - name: Install AVR dependencies
        run: sudo apt-get install gcc-avr binutils-avr avr-libc

      - name: Build Arduino firmware
        run: |
          cd firmware
          make
          mv Joystick.hex Arduino_UNO_R3.hex
          cd ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-java-fx"
          prerelease: true
          title: "Development Build (JavaFX)"
          files: |
            LICENSE
            gui/client.jar
            gui/server.jar
            firmware/Arduino_UNO_R3.hex